### PR TITLE
Add support for Path Parameters

### PR DESCRIPTION
**Pull request by thapabishwa**
**Description**
This PR extends the capabilities by adding support for path parameters, which enhances functionality of `vcfvct/ts-lambda-local-dev` as a local development environment for AWS Lambda functions.

**Changes**
To achieve this, the pathParamsPattern configuration option is introduced, which defaults to '/'. It can be set to any pattern as needed.

This also replaces the default http server with an express http server. This change makes it easier to handle the path parameters as express provides an easy way to define route patterns and read parameters from routes.

**Usage**
To use the path parameters in LocalLambda, you can specify the pathParamsPattern configuration option in the LocalLambdaConfig object. This option takes a string value that defines the pattern of the path parameters in the API endpoint.

For example, you can set pathParamsPattern to `'/v1/users/:userID/tasks/:taskID'` to define a pattern with two path parameters - `userID` and `taskID`.

In your lambda function, you can then access these path parameters by accessing the pathParameters property of the event object. For example, `const { userID, taskID } = event.pathParameters` will extract the userID and taskID path parameters for further use in your lambda function.

**Tests**
To ensure backwards and forward compatibility, I tested this feature locally with existing and new components to verify that it functions properly.

### CODE REVIEW

**Comment by vcfvct** [comment]
Hi @thapabishwa , thanks for the contribution. Sorry for the late response. I just got back from vacation. 
For the PR, I am good with introducing `Express` as a dependency if path param parsing is not that straightforward with `http` module. I was trying to use the Node Core  module at the beginning for performance and simplicity.

@blakejoy , would you be able to try it in your use case? :)

**Comment by blakejoy** [comment]
> Hi @thapabishwa , thanks for the contribution. Sorry for the late response. I just got back from vacation. For the PR, I am good with introducing `Express` as a dependency if path param parsing is not that straightforward with `http` module. I was trying to use the Node Core module at the beginning for performance and simplicity.
> 
> @blakejoy , would you be able to try it in your use case? :)

Yeah I can test it out. I guess one thing I would recommend is bumping to a new major version with the introduction of express. It’s a little heavy to add just for path parsing. Is there any way to just reuse the logic express has to determine [params](https://github.com/expressjs/express/blob/508936853a6e311099c9985d4c11a4b1b8f6af07/lib/router/layer.js#L110) ?

**Comment by thapabishwa-plerionaut** [comment]
> > Hi @thapabishwa , thanks for the contribution. Sorry for the late response. I just got back from vacation. For the PR, I am good with introducing `Express` as a dependency if path param parsing is not that straightforward with `http` module. I was trying to use the Node Core module at the beginning for performance and simplicity.
> > @blakejoy , would you be able to try it in your use case? :)
> 
> Yeah I can test it out. I guess one thing I would recommend is bumping to a new major version with the introduction of express. It’s a little heavy to add just for path parsing. Is there any way to just reuse the logic express has to determine [params](https://github.com/expressjs/express/blob/508936853a6e311099c9985d4c11a4b1b8f6af07/lib/router/layer.js#L110) ?
Hello @blakejoy! I often work on a project that involves multiple lambda handlers in a single repository. And, I find it cumbersome to have to expose each handler on a different port, as it requires me to constantly switch ports.

Therefore, I am considering using Express Routing to expose all the handlers of a project on the same port but on different routes. 

PS: I'm currently working on this change and I believe this will be a more efficient approach and will offer more flexibility.

**Comment by thapabishwa** [comment]
> > Hi @thapabishwa , thanks for the contribution. Sorry for the late response. I just got back from vacation. For the PR, I am good with introducing `Express` as a dependency if path param parsing is not that straightforward with `http` module. I was trying to use the Node Core module at the beginning for performance and simplicity.
> > @blakejoy , would you be able to try it in your use case? :)
> 
> Yeah I can test it out. I guess one thing I would recommend is bumping to a new major version with the introduction of express. It’s a little heavy to add just for path parsing. Is there any way to just reuse the logic express has to determine [params](https://github.com/expressjs/express/blob/508936853a6e311099c9985d4c11a4b1b8f6af07/lib/router/layer.js#L110) ?

Hello @blakejoy! I attempted to use the same approach used by Express to determine the parameters, but it didn't yield satisfactory results. Therefore, I ended up using Express instead.

I often work on a project has multiple lambda handlers in a single repository. As such, managing several handlers that are exposed on a variety of ports can create a significant cognitive burden, both for myself and for new developers who are joining the project.

So, I introduced Express to this project with the intention of utilizing its Routing as well as its ability to handle path parameters. Once these functionalities are implemented, I will be able expose all the handlers on a single port, assign them to different routes, and extract any necessary parameters as well.

PS:  I'm in the process of implementing Express Routing. Like I mentioned before, it will allow us to expose multiple handlers on a single port while assigning them to different routes. And, I really think this will give us a lot more flexibility and options moving forward. Once this is all set up, I'm confident that it'll open up a whole new world of possibilities for us to take this project to the next level!

**Comment by vcfvct** [comment]
LGTM, it has some conflict with the other PR merged. can  you please resolve it? Thanks @thapabishwa 

@blakejoy , I guess we could merge this if everything works on your end also 😄

**Comment by thapabishwa** [comment]
> Spring break here is finally over. LGTM, it has some conflict with the other PR merged. can you please resolve it? Thanks @thapabishwa
> 
> @blakejoy , I guess we could merge this if everything works on your end also 😄

Done.

**Comment by blakejoy** [comment]
> Spring break here is finally over. LGTM, it has some conflict with the other PR merged. can you please resolve it? Thanks @thapabishwa
> 
> @blakejoy , I guess we could merge this if everything works on your end also 😄

Yup I’ll test this out on Monday

**Comment by blakejoy** [comment]
> > Spring break here is finally over. LGTM, it has some conflict with the other PR merged. can you please resolve it? Thanks @thapabishwa
> > @blakejoy , I guess we could merge this if everything works on your end also 😄
> 
> Yup I’ll test this out on Monday

Still need to look at this. Will try to do tomorrow.

**Comment by vcfvct** [comment]
@blakejoy This LGTM, I guess we could merge it if you do not have time to test for now. 
let me know 😄

**Review by vcfvct — APPROVED** [review]

**Comment by blakejoy** [comment]
> @blakejoy This LGTM, I guess we could merge it if you do not have time to test for now.
> let me know 😄

Tested this morning. All looks good. My bad for the late reply

**Review by blakejoy — APPROVED** [review]

**Pull request merged**
